import React,{Component} from 'react';
import './policy.css';

class Policy extends Component {
    render(){
        return(
            <div className="container" id="pol">
                <a href="/signup" id="li">Go back...</a>
                <h1>Free Membership Agreement</h1>
                <h3>Part A:  New version - updated on May 6th, 2020 and effective as of May 6th, 2020</h3>
                <br/>
                    <p>
                        
                        PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY! PLEASE PAY ATTENTION TO PROVISIONS THAT EXCLUDE OR LIMIT LIABILITY AND TERMS OF GOVERNING LAW AND JURISDICTION, WHICH MAY APPEAR IN CAPITAL LETTERS. THIS AGREEMENT RELATES TO WWW.ALIBABA.COM, WWW.ALIEXPRESS.COM, WWW.ALIEXPRESS.RU, AND WWW.TMALL.RU.

                        1.  ACCEPTANCE OF TERMS

                        1.1    WELCOME TO ALIBABA.COM'S FREE SERVICE (the "SERVICE"). The following sets forth the terms and conditions of the Alibaba.com Free Membership Agreement (this "Agreement") between you (“Member”) and the Alibaba.com contracting company determined in accordance with this clause 1.1 ("Alibaba.com") under which Alibaba.com offers you access to and use of the Service through the websites, mobile sites, mobile applications and other portals owned, operated, branded or made available by Alibaba.com to you from time to time relating to (a) the Alibaba e-commerce platform including but not limited to the web and mobile-optimized versions of the websites identified by the uniform resource locator “www.alibaba.com” and the mobile applications of the Alibaba.com e-commerce platform (collectively the “Alibaba Sites”); and (b) the AliExpress e-commerce platform including but not limited to the web and mobile-optimized versions of the websites identified by the uniform resource locator “www.aliexpress.com”, “www.aliexpress.ru” and “www.tmall.ru”, and the mobile applications of the AliExpress e-commerce platforms, (collectively the “AliExpress Sites”), (with Alibaba Sites and AliExpress Sites collectively the “Sites”).

                        Contracting Alibaba.com party:

                            If you are from mainland China, your contract is with Hangzhou Alibaba Advertising Co., Ltd, other than in relation to Promotion Services (as defined in the Alibaba.com Terms of Use, currently at https://rule.alibaba.com/rule/detail/2041.htm), in which case your contract for such services is with Alibaba.com Hong Kong Limited. 
                            If you are from Hong Kong and Macau, your contract is with Alibaba.com Hong Kong Limited. 
                            If either (i) you are from a place outside mainland China, Hong Kong, Macau; or (ii) you access and use the Alibaba Sites from any of the Relevant Jurisdictions, your contract is with Alibaba.com Singapore E-Commerce Private Limited (incorporated in Singapore with Company Reg. No. 200720572D).
                            Notwithstanding anything to the contrary in the forgoing paragraphs (a), (b) and (c), if you are resident in or access and use AliExpress Sites from any of the Relevant Jurisdictions (the “AliExpress Relevant Jurisdiction User”), your contract is with AliExpress Russia Holding Private Limited (incorporated in Singapore with Company Reg. No. 201917627W). “Relevant Jurisdictions” shall mean the Russian Federation, Azerbaijan, Armenia, Belarus, Georgia, Kazakhstan, Kyrgyzstan, Moldova, Turkmenistan, Tajikistan and Uzbekistan.

                        

                        As some or part of the Service may be supported and provided by affiliates of Alibaba.com, Alibaba.com may delegate some aspects of the Service to its affiliates. Use of the Service indicates that you accept the terms and conditions set forth below. If you do not accept all of the terms and conditions, please do not use the Service. BY COMPLETING THE REGISTRATION PROCESS AND CLICKING THE "I AGREE" BUTTON, YOU ARE INDICATING YOUR CONSENT TO BE BOUND BY THIS AGREEMENT, THE SITE’S TERMS OF USE AGREEMENT, PRODUCT LISTING POLICY AND PRIVACY POLICY (DEFINED BELOW) WHICH ARE INCORPORATED HEREIN BY REFERENCE (COLLECTIVELY REFERRED TO AS THE "TERMS OF USE"). The Alibaba.com Free Membership Agreement will not take effect unless and until you have activated your Account. Terms not defined in this Agreement shall bear the same meaning as that contained in the Terms of Use.

                        1.2   Alibaba.com may amend this Agreement at any time by posting the amended and restated Agreement on the Sites. The amended and restated Agreement shall be effective immediately upon posting. Posting by Alibaba.com of the amended and restated Agreement and your continued use of the Service shall be deemed to be acceptance of the amended terms.

                        2.  THE SERVICE

                        2.1   The Service will be offered free-of-charge for an unspecified time period unless terminated in accordance with the terms of this Agreement.

                        2.2    The Service will have the following core features (which may be added to or modified, or suspended for scheduled or unscheduled maintenance purposes, from time to time at the sole discretion of Alibaba.com and notified to you) ("Free Member Benefits"):

                        a) Company Profile - allows each Member to display and edit basic information about its business, such as year and place of establishment, estimated annual sales, number of employees, and products and services offered, etc.

                        b) Products - allows each Member to display and edit descriptions, specifications and images of at least 5 products.

                        c) Unlimited Buyer Trade Lead Posting - allows each Member to post on the Sites for public display offers to buy products and services from other users of the Sites.

                        2.3    Alibaba.com may suspend or terminate all or part of the above Free Member Benefits at any time in its sole discretion without liability for any losses or damages arising out of or in connection with such suspension or termination. Alibaba.com reserves the right to charge for the Service or any feature or functionality of the Service at any time in its sole discretion.

                        2.4    Benefits, features and functions available to a Member may vary for different countries and regions.  No warranty or representation is given that a particular feature or function or the same type and extent of features and functions will be available.

                        2.5    The availability of any transactional features and functions on the Sites to any Member may be conditional on verification of Member’s identity and/or its designated bank account by Alibaba.com and/or its approved independent third parties.

                        2.6    Alibaba.com shall issue a Member ID and Password (the latter shall be chosen by the Member during registration) to each Member to access the Service through such Member's Account. Each Member shall be solely responsible for maintaining the confidentiality of its Member ID and Password and for all use of and activities that occur under the Member ID and Password (whether such use or activities are authorized or not). A set of Member ID and Password is unique to a single Account and no Member shall share, assign or permit the use of its Account, Member ID or Password to another person, even to other individuals within the Member's own business entity (where applicable). Each Member acknowledges that sharing of its Account with other persons, or allowing multiple users outside of its business entity to use its Account (collectively, "multiple use"), may cause irreparable harm to Alibaba.com and each Member shall indemnify Alibaba.com against any loss or damages (including but not limited to loss of profits) suffered by Alibaba.com as a result of such multiple use of an Account. Each Member hereby undertakes to notify Alibaba.com immediately of any unauthorized use of its Account, Member ID or Password or any other breach of security. Each Member hereby agrees that Alibaba.com shall not be liable for any loss or damages arising from the Member's failure to comply with this paragraph.

                        2.7    Alibaba.com reserves the right to change, upgrade, modify, limit or suspend the Service or any of its related functionalities or applications at any time temporarily or permanently without prior notice, except in respect of any AliExpress Relevant Jurisdiction Users. Alibaba.com further reserves the right but shall not be obliged to introduce new features, functionalities, applications or conditions to the Service or to future versions of the Service, except in respect of any AliExpress Relevant Jurisdiction Users. All new features, functionalities, applications, conditions, modifications, upgrades and alterations shall be governed by this Agreement, unless otherwise stated by Alibaba.com. In respect of any AliExpress Relevant Jurisdiction Users, AliExpress Russia Holding Private Limited is the relevant party.

                        2.8    Each Member acknowledges that inability to use the Service wholly or partially for whatever reason may have adverse effects on its business. Each Member hereby agrees that in no event shall Alibaba.com be liable to the Member or any third parties for any inability to use the Service (whether due to disruption, changes to or termination of the Service or otherwise), any delays, inaccuracies, errors or omissions with respect to any communications or transmission or delivery of all or any part thereof, or any losses or damages (direct, indirect, consequential or otherwise) arising from the use of or inability to use the Service.

                        2.9    If your IP address comes from the mainland China when you successfully complete the registration with Alibaba.com Free Membership, you will be granted an Alipay Username in addition to your Member ID.  If your registration was completed before March 18, 2013 or the email address you used for your registration has already been registered with other Alibaba Sites (as defined below), you will not be granted the Alipay Username.  You are allowed to use the Alipay Username to login to the websites including www.alipay.com, www.taobao.com, www.tmall.com, www.etao.com, www.ju.taobao.com, www.aliyun.com, www.china.alibaba.com and other websites (collectively, the “Alibaba Sites”). You hereby represent and agree to authorize Alibaba.com to provide all the information associated with your Member ID to the Alibaba Sites for the purpose of facilitating your easy and fast access to the Alibaba Sites.  Your responsibilities with regard to the Alipay Username shall apply to the same terms and conditions in connection with the Member ID as prescribed under this Agreement.  Alibaba.com reserves the right, without prior notice and at its sole discretion, to suspend, restrict or deny access to or use of your Alipay Username and services provided by Alibaba.com and Alibaba Sites without liability for any losses or damages arising out of or in connection with such suspension or termination, if you: (a) use the services provided by Alibaba.com, or through the Sites and the Alibaba Sites to defraud any person or entity; (b) engage in any unlawful activities including without limitation those which would constitute the infringement of intellectual property rights, a civil liability or a criminal offence; (c) engage in any activities that would otherwise create any liability for Alibaba.com, the Sites or the Alibaba Sites.

                        2.10 If you voluntarily submit any information to the Sites for publication on the Sites through the publishing tools, including but not limited to, company or business profile, product catalog, trade leads, TRUSTPASS profile, business trust system and any discussion forum, then you are deemed to have given consent to the publication of such information on the Sites.

                        3.   MEMBER RESPONSIBILITIES

                        3.1    Each Member hereby represents, warrants and agrees to (a) provide true, accurate, current and complete information about itself and its business references as may be required by Alibaba.com and (b) maintain and promptly amend all information to keep it true, accurate, current and complete. To the extent permitted under applicable laws, each Member hereby grants an irrevocable, perpetual, worldwide and royalty-free, sub-licensable (through multiple tiers) license to Alibaba.com to display and use all information provided by such Member in accordance with the purposes set forth in this Agreement and to exercise the copyright, publicity, and database rights you have in such material or information, in any media now known or not currently known. Information that is protected under data protection laws will only be used and kept in compliance with those laws.

                        3.2    Each Member hereby represents, warrants and agrees that the use by such Member of the Service and the Sites shall not:

                        a) contain fraudulent information or make fraudulent offers of items or involve the sale or attempted sale of counterfeit or stolen items or items whose sales and/or marketing is prohibited by applicable law, or otherwise promote other illegal activities;

                        b) be part of a scheme to defraud other Members or other users of the Sites or for any other unlawful purpose;

                        c) infringe or otherwise abet or encourage the infringement or violation of any third party's copyright, patent, trademarks, trade secret or other proprietary right or rights of publicity and privacy or other legitimate rights;

                        d) impersonate any person or entity, misrepresent yourself or your affiliation with any person or entity;

                        e) violate any applicable law, statute, ordinance or regulation (including without limitation those governing export control, consumer protection, unfair competition, anti-discrimination or false advertising);

                        f) contain information that is defamatory, libelous, unlawfully threatening or unlawfully harassing;

                        g) contain information that is obscene or contain or infer any pornography or sex-related merchandising or any other content or otherwise promotes sexually explicit materials or is otherwise harmful to minors;

                        h) promote discrimination based on race, sex, religion, nationality, disability, sexual orientation or age;

                        i) contain any material that constitutes unauthorized advertising or harassment (including but not limited to spamming), invades anyone's privacy or encourages conduct that would constitute a criminal offence, give rise to civil liability, or otherwise violate any law or regulation;

                        j) involve attempts to copy, reproduce, exploit or expropriate Alibaba.com's various proprietary directories, databases and listings;

                        k) involve any computer viruses or other destructive devices and codes that have the effect of damaging, interfering with, intercepting or expropriating any software or hardware system, data or personal information; and

                        l) involve any scheme to undermine the integrity of the computer systems or networks used by Alibaba.com and/or any user of the Service and no Member shall attempt to gain unauthorized access to such computer systems or networks;

                        m) link directly or indirectly to or include descriptions of goods or services or other materials that violate any law or regulation or are prohibited under this Agreement or the Terms of Use; or

                        n) otherwise create any liability for Alibaba.com or its affiliates.

                        3.3 Each Member represents, warrants and agrees that with regards to information about or posted on behalf of any business referee, it has obtained all necessary consents, approvals and waivers from such referee to (a) act as such Member's business referee; (b) to post and publish their contact details and information, reference letters and comments on their behalf; and (c) that third parties may contact such business referees to support claims or statements made about the Member. Each Member further warrants that all reference letters and comments are true and accurate and hereby waives all requirements for such Member's consent to be obtained before third parties may contact the business referees.

                        3.4 Member shall not take any action which may undermine the integrity of Alibaba.com's feedback system, such as leaving positive feedback for himself using secondary Member IDs or through third parties or by leaving unsubstantiated negative feedback for another Member.

                        3.5 Each Member acknowledges and agrees that Alibaba.com reserves the right to, but shall not be required to actively monitor nor exercise any editorial control whatsoever over the content of any message or other material or information created, obtained or accessible through the Service. Alibaba.com does not endorse, verify or otherwise certify the contents of any comments or other material or information made by any Member. Each Member is solely responsible for the contents of their communications and may be held legally liable or accountable for the content of their comments or other material or information.

                        3.6 Each Member represents, warrants and agrees that it has obtained all necessary third party licenses and permissions and shall be solely responsible for ensuring that any material or information it posts on the Sites or provides to Alibaba.com or authorizes Alibaba.com to display does not violate the copyright, patent, trademark, trade secrets or any other personal or proprietary rights of any third party or is posted with the permission of the owner(s) of such rights. Each Member further represents, warrants and agrees that it has the right and authority to sell, distribute or offer to sell or distribute the products described in the material or information it posts on the Sites or provides to Alibaba.com or authorizes Alibaba.com to display.

                        3.7 If any Member breaches the representations, warranties and covenants of paragraphs 3.1, 3.2, 3.3, 3.4, 3.5 or 3.6 above, or if Alibaba.com has reasonable grounds to believe that such Member is in breach of such representations, warranties and covenants, or if upon complaint or claim from any other Member or third party, Alibaba.com has reasonable grounds to believe that such Member has willfully or materially failed to perform its contract with such third party including without limitation where a Member who supplies products or services using the Sites and Services has failed to deliver any items ordered by such third party after receipt of the purchase price, or where such Member has delivered the items that materially fail to meet the terms and descriptions outlined in its contract with such third party, or if Alibaba.com has reasonable grounds to believe that such Member has used a stolen credit card or other false or misleading information in any online transaction, Alibaba.com has the right to suspend or terminate the Service and all Free Member Benefits with respect to such Member without compensation and without liability for any losses or damages arising out of or in connection with such suspension or termination, and restrict or refuse any and all current or future use of the Service or any other services that may be provided by Alibaba.com. Further, Alibaba.com reserves the right in its sole discretion to place restrictions on the number of product listings that a Member can post on the Sites for such duration as Alibaba.com may consider appropriate, and to remove any material it reasonably believes that is unlawful, could subject Alibaba.com to liability, violates this Agreement or the Terms of Use or is otherwise found inappropriate in Alibaba.com's opinion. Alibaba.com reserves the right to cooperate fully with governmental and regulatory authorities, law enforcement bodies, private investigators and/or injured third parties in the investigation of any suspected criminal or civil wrongdoing. Further, to the extent permitted under applicable laws and policies, Alibaba.com may disclose the Member's identity, contact information and/or information regarding the Member's account(s), transactions or activities carried out on or via the Sites, if requested by a government, regulatory or law enforcement body or an injured third party, or as a result of a subpoena or other legal action, and Alibaba.com shall not be liable for damages or results thereof and Member agrees not to bring any action or claim against Alibaba.com for such disclosure. In connection with any of the foregoing, Alibaba.com may suspend or terminate the Account of any Member as Alibaba.com deems appropriate in its sole discretion.

                        3.8 Each Member agrees to indemnify Alibaba.com, its employees, agents and representatives and to hold them harmless, from any and all losses, claims and liabilities (including legal costs on a full indemnity basis) which may arise from its submissions, posting of materials or deletion thereof, from such Member's use of the Service or from such Member's breach of this Agreement or the Terms of Use. Each Member further agrees that Alibaba.com is not responsible, and shall have no liability to it or anyone else for any material posted by such Member or third parties, including fraudulent, untrue, misleading, inaccurate, defamatory, offensive or illicit material and that the risk of damage from such material rests entirely with each Member. Alibaba.com reserves the right; at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by the Member, in which event the Member shall cooperate with Alibaba.com in asserting any available defenses.

                        4.   TRANSACTIONS BETWEEN BUYERS AND SUPPLIERS

                        4.1 Through the Sites, Alibaba.com provides an electronic web-based platform for exchanging information and concluding sale and purchase transactions of products and services online between buyers and suppliers. Alibaba.com reserves the right to limit certain features and functions of the platform to prescribed Members.  Despite the provision of the platform through the Sites, Alibaba.com does not represent the seller or the buyer in specific transactions whether or not such transactions are made on or via the Sites. Alibaba.com does not control and is not liable to or responsible for the quality, safety, lawfulness or availability of the products or services offered for sale on the Sites or the ability of the suppliers to complete a sale or the ability of buyers to complete a purchase.

                        4.2 Members are hereby made aware that there may be risks of dealing with people acting under false pretences. Alibaba.com uses several techniques to verify the accuracy of the information our users provide us when they register on the Sites. However, because user verification on the Internet is difficult, Alibaba.com cannot and does not confirm each free member's purported identity shown on the Sites and can only use reasonable efforts to verify the personal identity of the representative of a seller in mainland China opening a storefront on www.aliexpress.com according to the applicable laws in mainland China. We encourage you to use the various tools available on the Sites, as well as common sense, to evaluate with whom you are dealing.

                        4.3 Each Member accessing or using the Sites or Service shall fully assume the risks of conducting any purchase and sale transactions in connection with or through the Sites or Service . Such risks shall include, but not limited to, mis-representation of products and services, fraudulent schemes, unsatisfactory quality, failure to meet specifications, defective products, delay or default in delivery or payment, cost mis-calculations, breach of warranty, breach of contract and transportation accidents ("Transaction Risks"). Each Member agrees that Alibaba.com shall not be liable or responsible for any damages, liabilities, costs, harms, inconveniences, business disruptions or expenditures of any kind that may arise a result of or in connection with any Transaction Risks.

                        4.4 Members are solely responsible for setting out, agreeing on, entering into and performing all of the terms and conditions of the transactions conducted on, through or as a result of use of the Sites, including, without limitation, terms regarding payment, returns, warranties, shipping, insurance, fees, taxes, title, licenses, fines, permits, handling, transportation and storage, subject to any additional obligations imposed under the Transactional Services Agreement (and in particular, clause 3.2).

                        4.5 Member agrees to provide all information and materials as may be reasonably required by Alibaba.com in connection with its transactions made via the transactional platform on the Sites.  Alibaba.com has the right to suspend or terminate any Member’s Account if the Member fails to provide the required information and materials without liability for any losses or damages arising out of or in connection with such suspension or termination.

                        4.6 In the event that any Member has a dispute with any party to a transaction, such Member agrees to release and indemnify Alibaba.com (and our agents, affiliates, directors, officers and employees) from all claims, demands, actions, proceedings, costs, expenses and damages (including without limitation any actual, special, incidental or consequential damages) arising out of or in connection with such dispute or the transaction.
                        </p>
                    </div>
                    
        )
    }
}
export default Policy;


{/* <div className="col-3">
                        <p>Policy</p>
                    </div>
                    <div className="col-6" id="pol">
                        <p>
                        Free Membership Agreement


                        Part A:  New version - updated on May 6th, 2020 and effective as of May 6th, 2020

                        PLEASE READ THESE TERMS AND CONDITIONS CAREFULLY! PLEASE PAY ATTENTION TO PROVISIONS THAT EXCLUDE OR LIMIT LIABILITY AND TERMS OF GOVERNING LAW AND JURISDICTION, WHICH MAY APPEAR IN CAPITAL LETTERS. THIS AGREEMENT RELATES TO WWW.ALIBABA.COM, WWW.ALIEXPRESS.COM, WWW.ALIEXPRESS.RU, AND WWW.TMALL.RU.

                        1.  ACCEPTANCE OF TERMS

                        1.1    WELCOME TO ALIBABA.COM'S FREE SERVICE (the "SERVICE"). The following sets forth the terms and conditions of the Alibaba.com Free Membership Agreement (this "Agreement") between you (“Member”) and the Alibaba.com contracting company determined in accordance with this clause 1.1 ("Alibaba.com") under which Alibaba.com offers you access to and use of the Service through the websites, mobile sites, mobile applications and other portals owned, operated, branded or made available by Alibaba.com to you from time to time relating to (a) the Alibaba e-commerce platform including but not limited to the web and mobile-optimized versions of the websites identified by the uniform resource locator “www.alibaba.com” and the mobile applications of the Alibaba.com e-commerce platform (collectively the “Alibaba Sites”); and (b) the AliExpress e-commerce platform including but not limited to the web and mobile-optimized versions of the websites identified by the uniform resource locator “www.aliexpress.com”, “www.aliexpress.ru” and “www.tmall.ru”, and the mobile applications of the AliExpress e-commerce platforms, (collectively the “AliExpress Sites”), (with Alibaba Sites and AliExpress Sites collectively the “Sites”).

                        Contracting Alibaba.com party:

                            If you are from mainland China, your contract is with Hangzhou Alibaba Advertising Co., Ltd, other than in relation to Promotion Services (as defined in the Alibaba.com Terms of Use, currently at https://rule.alibaba.com/rule/detail/2041.htm), in which case your contract for such services is with Alibaba.com Hong Kong Limited. 
                            If you are from Hong Kong and Macau, your contract is with Alibaba.com Hong Kong Limited. 
                            If either (i) you are from a place outside mainland China, Hong Kong, Macau; or (ii) you access and use the Alibaba Sites from any of the Relevant Jurisdictions, your contract is with Alibaba.com Singapore E-Commerce Private Limited (incorporated in Singapore with Company Reg. No. 200720572D).
                            Notwithstanding anything to the contrary in the forgoing paragraphs (a), (b) and (c), if you are resident in or access and use AliExpress Sites from any of the Relevant Jurisdictions (the “AliExpress Relevant Jurisdiction User”), your contract is with AliExpress Russia Holding Private Limited (incorporated in Singapore with Company Reg. No. 201917627W). “Relevant Jurisdictions” shall mean the Russian Federation, Azerbaijan, Armenia, Belarus, Georgia, Kazakhstan, Kyrgyzstan, Moldova, Turkmenistan, Tajikistan and Uzbekistan.

                        

                        As some or part of the Service may be supported and provided by affiliates of Alibaba.com, Alibaba.com may delegate some aspects of the Service to its affiliates. Use of the Service indicates that you accept the terms and conditions set forth below. If you do not accept all of the terms and conditions, please do not use the Service. BY COMPLETING THE REGISTRATION PROCESS AND CLICKING THE "I AGREE" BUTTON, YOU ARE INDICATING YOUR CONSENT TO BE BOUND BY THIS AGREEMENT, THE SITE’S TERMS OF USE AGREEMENT, PRODUCT LISTING POLICY AND PRIVACY POLICY (DEFINED BELOW) WHICH ARE INCORPORATED HEREIN BY REFERENCE (COLLECTIVELY REFERRED TO AS THE "TERMS OF USE"). The Alibaba.com Free Membership Agreement will not take effect unless and until you have activated your Account. Terms not defined in this Agreement shall bear the same meaning as that contained in the Terms of Use.

                        1.2   Alibaba.com may amend this Agreement at any time by posting the amended and restated Agreement on the Sites. The amended and restated Agreement shall be effective immediately upon posting. Posting by Alibaba.com of the amended and restated Agreement and your continued use of the Service shall be deemed to be acceptance of the amended terms.

                        2.  THE SERVICE

                        2.1   The Service will be offered free-of-charge for an unspecified time period unless terminated in accordance with the terms of this Agreement.

                        2.2    The Service will have the following core features (which may be added to or modified, or suspended for scheduled or unscheduled maintenance purposes, from time to time at the sole discretion of Alibaba.com and notified to you) ("Free Member Benefits"):

                        a) Company Profile - allows each Member to display and edit basic information about its business, such as year and place of establishment, estimated annual sales, number of employees, and products and services offered, etc.

                        b) Products - allows each Member to display and edit descriptions, specifications and images of at least 5 products.

                        c) Unlimited Buyer Trade Lead Posting - allows each Member to post on the Sites for public display offers to buy products and services from other users of the Sites.

                        2.3    Alibaba.com may suspend or terminate all or part of the above Free Member Benefits at any time in its sole discretion without liability for any losses or damages arising out of or in connection with such suspension or termination. Alibaba.com reserves the right to charge for the Service or any feature or functionality of the Service at any time in its sole discretion.

                        2.4    Benefits, features and functions available to a Member may vary for different countries and regions.  No warranty or representation is given that a particular feature or function or the same type and extent of features and functions will be available.

                        2.5    The availability of any transactional features and functions on the Sites to any Member may be conditional on verification of Member’s identity and/or its designated bank account by Alibaba.com and/or its approved independent third parties.

                        2.6    Alibaba.com shall issue a Member ID and Password (the latter shall be chosen by the Member during registration) to each Member to access the Service through such Member's Account. Each Member shall be solely responsible for maintaining the confidentiality of its Member ID and Password and for all use of and activities that occur under the Member ID and Password (whether such use or activities are authorized or not). A set of Member ID and Password is unique to a single Account and no Member shall share, assign or permit the use of its Account, Member ID or Password to another person, even to other individuals within the Member's own business entity (where applicable). Each Member acknowledges that sharing of its Account with other persons, or allowing multiple users outside of its business entity to use its Account (collectively, "multiple use"), may cause irreparable harm to Alibaba.com and each Member shall indemnify Alibaba.com against any loss or damages (including but not limited to loss of profits) suffered by Alibaba.com as a result of such multiple use of an Account. Each Member hereby undertakes to notify Alibaba.com immediately of any unauthorized use of its Account, Member ID or Password or any other breach of security. Each Member hereby agrees that Alibaba.com shall not be liable for any loss or damages arising from the Member's failure to comply with this paragraph.

                        2.7    Alibaba.com reserves the right to change, upgrade, modify, limit or suspend the Service or any of its related functionalities or applications at any time temporarily or permanently without prior notice, except in respect of any AliExpress Relevant Jurisdiction Users. Alibaba.com further reserves the right but shall not be obliged to introduce new features, functionalities, applications or conditions to the Service or to future versions of the Service, except in respect of any AliExpress Relevant Jurisdiction Users. All new features, functionalities, applications, conditions, modifications, upgrades and alterations shall be governed by this Agreement, unless otherwise stated by Alibaba.com. In respect of any AliExpress Relevant Jurisdiction Users, AliExpress Russia Holding Private Limited is the relevant party.

                        2.8    Each Member acknowledges that inability to use the Service wholly or partially for whatever reason may have adverse effects on its business. Each Member hereby agrees that in no event shall Alibaba.com be liable to the Member or any third parties for any inability to use the Service (whether due to disruption, changes to or termination of the Service or otherwise), any delays, inaccuracies, errors or omissions with respect to any communications or transmission or delivery of all or any part thereof, or any losses or damages (direct, indirect, consequential or otherwise) arising from the use of or inability to use the Service.

                        2.9    If your IP address comes from the mainland China when you successfully complete the registration with Alibaba.com Free Membership, you will be granted an Alipay Username in addition to your Member ID.  If your registration was completed before March 18, 2013 or the email address you used for your registration has already been registered with other Alibaba Sites (as defined below), you will not be granted the Alipay Username.  You are allowed to use the Alipay Username to login to the websites including www.alipay.com, www.taobao.com, www.tmall.com, www.etao.com, www.ju.taobao.com, www.aliyun.com, www.china.alibaba.com and other websites (collectively, the “Alibaba Sites”). You hereby represent and agree to authorize Alibaba.com to provide all the information associated with your Member ID to the Alibaba Sites for the purpose of facilitating your easy and fast access to the Alibaba Sites.  Your responsibilities with regard to the Alipay Username shall apply to the same terms and conditions in connection with the Member ID as prescribed under this Agreement.  Alibaba.com reserves the right, without prior notice and at its sole discretion, to suspend, restrict or deny access to or use of your Alipay Username and services provided by Alibaba.com and Alibaba Sites without liability for any losses or damages arising out of or in connection with such suspension or termination, if you: (a) use the services provided by Alibaba.com, or through the Sites and the Alibaba Sites to defraud any person or entity; (b) engage in any unlawful activities including without limitation those which would constitute the infringement of intellectual property rights, a civil liability or a criminal offence; (c) engage in any activities that would otherwise create any liability for Alibaba.com, the Sites or the Alibaba Sites.

                        2.10 If you voluntarily submit any information to the Sites for publication on the Sites through the publishing tools, including but not limited to, company or business profile, product catalog, trade leads, TRUSTPASS profile, business trust system and any discussion forum, then you are deemed to have given consent to the publication of such information on the Sites.

                        3.   MEMBER RESPONSIBILITIES

                        3.1    Each Member hereby represents, warrants and agrees to (a) provide true, accurate, current and complete information about itself and its business references as may be required by Alibaba.com and (b) maintain and promptly amend all information to keep it true, accurate, current and complete. To the extent permitted under applicable laws, each Member hereby grants an irrevocable, perpetual, worldwide and royalty-free, sub-licensable (through multiple tiers) license to Alibaba.com to display and use all information provided by such Member in accordance with the purposes set forth in this Agreement and to exercise the copyright, publicity, and database rights you have in such material or information, in any media now known or not currently known. Information that is protected under data protection laws will only be used and kept in compliance with those laws.

                        3.2    Each Member hereby represents, warrants and agrees that the use by such Member of the Service and the Sites shall not:

                        a) contain fraudulent information or make fraudulent offers of items or involve the sale or attempted sale of counterfeit or stolen items or items whose sales and/or marketing is prohibited by applicable law, or otherwise promote other illegal activities;

                        b) be part of a scheme to defraud other Members or other users of the Sites or for any other unlawful purpose;

                        c) infringe or otherwise abet or encourage the infringement or violation of any third party's copyright, patent, trademarks, trade secret or other proprietary right or rights of publicity and privacy or other legitimate rights;

                        d) impersonate any person or entity, misrepresent yourself or your affiliation with any person or entity;

                        e) violate any applicable law, statute, ordinance or regulation (including without limitation those governing export control, consumer protection, unfair competition, anti-discrimination or false advertising);

                        f) contain information that is defamatory, libelous, unlawfully threatening or unlawfully harassing;

                        g) contain information that is obscene or contain or infer any pornography or sex-related merchandising or any other content or otherwise promotes sexually explicit materials or is otherwise harmful to minors;

                        h) promote discrimination based on race, sex, religion, nationality, disability, sexual orientation or age;

                        i) contain any material that constitutes unauthorized advertising or harassment (including but not limited to spamming), invades anyone's privacy or encourages conduct that would constitute a criminal offence, give rise to civil liability, or otherwise violate any law or regulation;

                        j) involve attempts to copy, reproduce, exploit or expropriate Alibaba.com's various proprietary directories, databases and listings;

                        k) involve any computer viruses or other destructive devices and codes that have the effect of damaging, interfering with, intercepting or expropriating any software or hardware system, data or personal information; and

                        l) involve any scheme to undermine the integrity of the computer systems or networks used by Alibaba.com and/or any user of the Service and no Member shall attempt to gain unauthorized access to such computer systems or networks;

                        m) link directly or indirectly to or include descriptions of goods or services or other materials that violate any law or regulation or are prohibited under this Agreement or the Terms of Use; or

                        n) otherwise create any liability for Alibaba.com or its affiliates.

                        3.3 Each Member represents, warrants and agrees that with regards to information about or posted on behalf of any business referee, it has obtained all necessary consents, approvals and waivers from such referee to (a) act as such Member's business referee; (b) to post and publish their contact details and information, reference letters and comments on their behalf; and (c) that third parties may contact such business referees to support claims or statements made about the Member. Each Member further warrants that all reference letters and comments are true and accurate and hereby waives all requirements for such Member's consent to be obtained before third parties may contact the business referees.

                        3.4 Member shall not take any action which may undermine the integrity of Alibaba.com's feedback system, such as leaving positive feedback for himself using secondary Member IDs or through third parties or by leaving unsubstantiated negative feedback for another Member.

                        3.5 Each Member acknowledges and agrees that Alibaba.com reserves the right to, but shall not be required to actively monitor nor exercise any editorial control whatsoever over the content of any message or other material or information created, obtained or accessible through the Service. Alibaba.com does not endorse, verify or otherwise certify the contents of any comments or other material or information made by any Member. Each Member is solely responsible for the contents of their communications and may be held legally liable or accountable for the content of their comments or other material or information.

                        3.6 Each Member represents, warrants and agrees that it has obtained all necessary third party licenses and permissions and shall be solely responsible for ensuring that any material or information it posts on the Sites or provides to Alibaba.com or authorizes Alibaba.com to display does not violate the copyright, patent, trademark, trade secrets or any other personal or proprietary rights of any third party or is posted with the permission of the owner(s) of such rights. Each Member further represents, warrants and agrees that it has the right and authority to sell, distribute or offer to sell or distribute the products described in the material or information it posts on the Sites or provides to Alibaba.com or authorizes Alibaba.com to display.

                        3.7 If any Member breaches the representations, warranties and covenants of paragraphs 3.1, 3.2, 3.3, 3.4, 3.5 or 3.6 above, or if Alibaba.com has reasonable grounds to believe that such Member is in breach of such representations, warranties and covenants, or if upon complaint or claim from any other Member or third party, Alibaba.com has reasonable grounds to believe that such Member has willfully or materially failed to perform its contract with such third party including without limitation where a Member who supplies products or services using the Sites and Services has failed to deliver any items ordered by such third party after receipt of the purchase price, or where such Member has delivered the items that materially fail to meet the terms and descriptions outlined in its contract with such third party, or if Alibaba.com has reasonable grounds to believe that such Member has used a stolen credit card or other false or misleading information in any online transaction, Alibaba.com has the right to suspend or terminate the Service and all Free Member Benefits with respect to such Member without compensation and without liability for any losses or damages arising out of or in connection with such suspension or termination, and restrict or refuse any and all current or future use of the Service or any other services that may be provided by Alibaba.com. Further, Alibaba.com reserves the right in its sole discretion to place restrictions on the number of product listings that a Member can post on the Sites for such duration as Alibaba.com may consider appropriate, and to remove any material it reasonably believes that is unlawful, could subject Alibaba.com to liability, violates this Agreement or the Terms of Use or is otherwise found inappropriate in Alibaba.com's opinion. Alibaba.com reserves the right to cooperate fully with governmental and regulatory authorities, law enforcement bodies, private investigators and/or injured third parties in the investigation of any suspected criminal or civil wrongdoing. Further, to the extent permitted under applicable laws and policies, Alibaba.com may disclose the Member's identity, contact information and/or information regarding the Member's account(s), transactions or activities carried out on or via the Sites, if requested by a government, regulatory or law enforcement body or an injured third party, or as a result of a subpoena or other legal action, and Alibaba.com shall not be liable for damages or results thereof and Member agrees not to bring any action or claim against Alibaba.com for such disclosure. In connection with any of the foregoing, Alibaba.com may suspend or terminate the Account of any Member as Alibaba.com deems appropriate in its sole discretion.

                        3.8 Each Member agrees to indemnify Alibaba.com, its employees, agents and representatives and to hold them harmless, from any and all losses, claims and liabilities (including legal costs on a full indemnity basis) which may arise from its submissions, posting of materials or deletion thereof, from such Member's use of the Service or from such Member's breach of this Agreement or the Terms of Use. Each Member further agrees that Alibaba.com is not responsible, and shall have no liability to it or anyone else for any material posted by such Member or third parties, including fraudulent, untrue, misleading, inaccurate, defamatory, offensive or illicit material and that the risk of damage from such material rests entirely with each Member. Alibaba.com reserves the right; at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by the Member, in which event the Member shall cooperate with Alibaba.com in asserting any available defenses.

                        4.   TRANSACTIONS BETWEEN BUYERS AND SUPPLIERS

                        4.1 Through the Sites, Alibaba.com provides an electronic web-based platform for exchanging information and concluding sale and purchase transactions of products and services online between buyers and suppliers. Alibaba.com reserves the right to limit certain features and functions of the platform to prescribed Members.  Despite the provision of the platform through the Sites, Alibaba.com does not represent the seller or the buyer in specific transactions whether or not such transactions are made on or via the Sites. Alibaba.com does not control and is not liable to or responsible for the quality, safety, lawfulness or availability of the products or services offered for sale on the Sites or the ability of the suppliers to complete a sale or the ability of buyers to complete a purchase.

                        4.2 Members are hereby made aware that there may be risks of dealing with people acting under false pretences. Alibaba.com uses several techniques to verify the accuracy of the information our users provide us when they register on the Sites. However, because user verification on the Internet is difficult, Alibaba.com cannot and does not confirm each free member's purported identity shown on the Sites and can only use reasonable efforts to verify the personal identity of the representative of a seller in mainland China opening a storefront on www.aliexpress.com according to the applicable laws in mainland China. We encourage you to use the various tools available on the Sites, as well as common sense, to evaluate with whom you are dealing.

                        4.3 Each Member accessing or using the Sites or Service shall fully assume the risks of conducting any purchase and sale transactions in connection with or through the Sites or Service . Such risks shall include, but not limited to, mis-representation of products and services, fraudulent schemes, unsatisfactory quality, failure to meet specifications, defective products, delay or default in delivery or payment, cost mis-calculations, breach of warranty, breach of contract and transportation accidents ("Transaction Risks"). Each Member agrees that Alibaba.com shall not be liable or responsible for any damages, liabilities, costs, harms, inconveniences, business disruptions or expenditures of any kind that may arise a result of or in connection with any Transaction Risks.

                        4.4 Members are solely responsible for setting out, agreeing on, entering into and performing all of the terms and conditions of the transactions conducted on, through or as a result of use of the Sites, including, without limitation, terms regarding payment, returns, warranties, shipping, insurance, fees, taxes, title, licenses, fines, permits, handling, transportation and storage, subject to any additional obligations imposed under the Transactional Services Agreement (and in particular, clause 3.2).

                        4.5 Member agrees to provide all information and materials as may be reasonably required by Alibaba.com in connection with its transactions made via the transactional platform on the Sites.  Alibaba.com has the right to suspend or terminate any Member’s Account if the Member fails to provide the required information and materials without liability for any losses or damages arising out of or in connection with such suspension or termination.

                        4.6 In the event that any Member has a dispute with any party to a transaction, such Member agrees to release and indemnify Alibaba.com (and our agents, affiliates, directors, officers and employees) from all claims, demands, actions, proceedings, costs, expenses and damages (including without limitation any actual, special, incidental or consequential damages) arising out of or in connection with such dispute or the transaction.
                        </p>
                    </div>
                    <div className="col-3">
                        <p>Policy</p>
                    </div>
                </div>
            </div> */}